### ISSUE TITLE
function getCompatibleFieldtypes is not compatible

### ISSUE THREAD

**Issue by kunago** [thuijzer/processwire-FieldtypeBusinessHours#1]
As of Processwire 3.0.140 there exists a new function in Fields.php called **getCompatibleFieldtypes**, which unfortunately breaks the Business hours fieldtype. This is the php error I get once I try to open the settings of the fields:

<pre>
Fatal Error: Uncaught Error: Call to a member function prepend() on null in /srv/www/wire/core/Fields.php:1066
Stack trace:
#0 /srv/www/wire/modules/Process/ProcessField/ProcessField.module(1412): ProcessWire\Fields->getCompatibleFieldtypes(Object(ProcessWire\Field))
#1 /srv/www/wire/core/Wire.php(380): ProcessWire\ProcessField->___buildEditFormBasics()
#2 /srv/www/wire/core/WireHooks.php(813): ProcessWire\Wire->_callMethod('___buildEditFor...', Array)
#3 /srv/www/wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessField), 'buildEditFormBa...', Array)
#4 /srv/www/wire/modules/Process/ProcessField/ProcessField.module(1020): ProcessWire\Wire->__call('buildEditFormBa...', Array)
#5 /srv/www/wire/core/Wire.php(380): ProcessWire\ProcessField->___buildEditForm()
#6 /srv/www/wire/core/WireHooks.php(813): ProcessWire\Wire->_callMethod('___buildEditFor...', Array)
#7 /srv/www/wire/core/Wire.php (line 1066 of /srv/www/wire/core/Fields.php)

This error message was shown because: you are logged in as a Superuser. Error has been logged.
</pre>

**Comment by kunago** [comment]
Maybe this would do? I borrowed part of the code from other modules and at least it does not trigger the error.

<pre>
    public function ___getCompatibleFieldtypes(Field $field)
    {
        return $this->wire(new Fieldtypes());
    }
</pre>

Unfortunately I don't really know what I am doing here so it is a trial and error.

**Comment by kunago** [comment]
I mark this as resolved as it works. I use this module on several sites and with this fix I have had no issues.
